apiVersion: apps/v1
kind: Deployment
metadata:
  name: upyogtemp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upyogtemp
  template:
    metadata:
      labels:
        app: upyogtemp
    spec:
      containers:
      - name: upyogtemp-container
        image: manyajainrkm/upyogtemp-image
        ports:
        - containerPort: 80
